### ISSUE TITLE
Sessions do not work with URL-encoded servers.

### ISSUE THREAD

**Issue by hypostulate** [klavinslab/benchling-api#34]
Some Benchling users have URLs of the form `"https://{my_org}.benchling.com/api/v2/"`, currently `Http` and subsequently `Session` are hardcoded to `"https://benchling.com/api/v2"`.

**To Reproduce**
1. Have a URL-encoded org

**Expected behavior**
Session accepts setting the `Http.HOME` url

**Comment by jvrana** [comment]
Thanks @hypostulate! 

This feature has now been merged with master and a new version released (2.1.12), now on PyPI.
I've slightly altered this feature. The new Session API is now:
```python
Session(api_key, org='myorganization')
# alternatively, setting homespace directly
Session(api_key, home='https://myorganization.benchling.com/api/v2')
```

Please see the [Session documentation](http://klavinslab.org/benchling-api/session.html) for more information.
