### ISSUE TITLE
Create DNA Sequence in Benchling from .gb file

### ISSUE THREAD

**Issue by avemeva** [klavinslab/benchling-api#42]
**Is your feature request related to a problem? Please describe.**
Create DNA Sequence in Benchling from .gb file

**Describe the solution you'd like**
Function which convert .gb file to DNA Sequence

**Describe alternatives you've considered**
I have used BioPython and manual way of conversion

**Additional context**
Currently Benchling does not support Import in its API. I have looked for such function in DNA Sequence model, as well as in utils file. Additional problem is that Benchling does not define the format of annotation field in its API, and in order to understand it I have to fetch the DNA sequence from benchling over API client and examine it.

**Comment by avemeva** [comment]
Solved for me with V1 Benchling API.

**Comment by shenker** [comment]
In case it's useful for anyone else, I use the following function to do the conversion: https://gist.github.com/shenker/374cd3108d537d07a84c6f86e4ac6a34
