### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by BjornFJohansson** [klavinslab/benchling-api#8]
Hi, this looks very interesting. What is your use case?

**Comment by jvrana** [comment]
Hi Bjorn,

Thanks for reaching out. I apologize for the thin documentation. I will be updating the documentation soon, as well as adding new **alignments** and **proteins** features to this API-wrapper.

This repo is just a python wrapper for [Benchling's API](https://api.benchling.com/docs/) with some extra convenience methods. Our lab collaborates with many other labs and groups and shares DNA mainly through Benchling, usually via the Benchling *share links.* Additionally, we use suite of different programs for designing DNAs (e.g. [Coral](https://github.com/klavinslab/coral)). This repo serves as a link between these software packages and the DNA data we store on Benchling. There are also some features provided by this repo that currently do not exist in Benchling that are very useful, mainly the 'search' function which allows you to search your entire Benchling database for a particular sequence or use regular expressions to find folders+sequences.

I use this repo for:
* Searching Benchling databases using regular expressions (e.g. find like anything with "Cas9" or "crispr" in the name)
* Searching entire Benchling database + collaborators databases for a particular DNA sequence or name
* Converting Benchling *share link* to gb or fasta format (as in a Jupyter Notebook)
* Quickly changing the names of hundreds of Benchling plasmids
* Quickly adding tags to hundreds of Benchling plasmids\
* Programmatically create new sequences that automatically upload to Benching (e.g. DNA libraries)
* Automatically submitting Benchling sequence alignments from Sanger sequencing data (e.g. scripts automatically fire a Benchling alignment when a folder sees a new .ab1 file)

**Comment by dgretton** [comment]
Hi @jvrana, extremely useful project. I'm still using v1 because we submit alignments; however, we're experiencing significant slowdown using v1 vs v2, probably benchling's way of encouraging us to upgrade. Any thoughts on upcoming alignment features?

**Comment by jvrana** [comment]
Hi @dgretton, I'm glad to hear its being used. DNA sequence alignments are currently supported in Benchling's API V2, but I have yet to create a method to support it. I've created another issue for this feature request #24

**Comment by jvrana** [comment]
@dgretton Creating sequence alignments is now supported in the new release (v2.1.4). You may view the documentation here: http://klavinslab.org/benchling-api/generated/benchlingapi.models.models.DNAAlignment.html#benchlingapi.models.models.DNAAlignment.submit_alignment
